#!/usr/bin/env python3
"""Write the curated, source-backed dilemma catalog."""

from __future__ import annotations

import json
from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "dilemmas.json"


def source(kind: str, title: str, url: str) -> dict[str, str]:
    return {"type": kind, "title": title, "url": url}


def entry(theme: str, text: str, citation: dict[str, str]) -> dict:
    return {"id": "", "theme": theme, "text": text, "source": citation}


W = "wikipedia"
E = "ethics_unwrapped"
O = "official"


CATALOG = [
    entry("The trolley switch", "A runaway trolley is heading toward five people trapped on the track. You can pull a lever to divert it onto a side track where one trapped person will die instead. You did not create the danger, and there is no time to warn anyone. Should you redirect the trolley, or refuse to intervene? Consider whether redirecting harm differs morally from allowing harm, and whether saving more lives settles the question.", source(W, "Trolley problem", "https://en.wikipedia.org/wiki/Trolley_problem")),
    entry("The footbridge stranger", "A runaway trolley will kill five people unless you push a large stranger from a footbridge onto the track. His body would stop the trolley, killing him but saving the five. He has not agreed to be used, and you can save the group only by deliberately making him the obstacle. Should you push him? Explain whether physical contact, intention, and the numbers affected change the answer.", source(W, "Trolley problem", "https://en.wikipedia.org/wiki/Trolley_problem")),
    entry("Heinz and the unaffordable medicine", "Heinz's spouse is dying from a rare illness. A pharmacist has developed a medicine that could save her, but charges $2,000 even though it cost about $200 to make. Heinz has borrowed only half the money, begged for a discount and a payment plan, and been refused. The pharmacist says the price protects the investment and that stealing is against the law. The medicine may be gone by morning. Should Heinz break into the pharmacy and take it? Discuss saving a life, respecting property, rewarding research, obeying the law, and accepting punishment afterward.", source(W, "Heinz dilemma", "https://en.wikipedia.org/wiki/Heinz_dilemma")),
    entry("The prisoner's bargain", "You and a trusted partner are arrested and questioned in separate rooms. If both of you remain silent, each receives one year. If one testifies against the other while the other stays silent, the witness goes free and the silent person receives ten years. If both testify, each receives five years. You cannot communicate. Should you stay silent, betray your partner, or choose based on what cooperation means when trust cannot be verified?", source(W, "Prisoner's dilemma", "https://en.wikipedia.org/wiki/Prisoner%27s_dilemma")),
    entry("The experience machine", "A machine can stimulate your brain so convincingly that you experience a lifetime of friendship, achievement, beauty, and pleasure. You would never know the experiences were simulated, but you would never make real choices or affect anyone outside the machine. You must choose before connecting and cannot leave once connected. Should you choose guaranteed wonderful experiences, or ordinary life with risk, frustration, real relationships, and the chance to accomplish something outside your mind?", source(W, "Experience machine", "https://en.wikipedia.org/wiki/Experience_machine")),
    entry("The plank of Carneades", "After a shipwreck, two strangers reach a floating plank that can support only one person. If neither acts, both drown; if one pushes the other away, the pusher survives. Neither caused the shipwreck, and there is no rescue in sight. Is pushing the other person off an unjust killing, permissible self-preservation, or a tragic act for which no one is fully responsible?", source(W, "Plank of Carneades", "https://en.wikipedia.org/wiki/Plank_of_Carneades")),
    entry("The ticking bomb", "A captured prisoner may know where a bomb is hidden in a city, and the bomb could kill thousands within an hour. Investigators have no proof that the prisoner knows the location, and torture may produce a false confession while violating an absolute ban on abuse. Should interrogators use torture to try to prevent the attack, or refuse even when the threatened harm is enormous?", source(W, "Ticking time bomb scenario", "https://en.wikipedia.org/wiki/Ticking_time_bomb_scenario")),
    entry("The nearby child and the distant child", "You pass a shallow pond and see a child drowning. You can save the child immediately, but your expensive clothes and shoes will be ruined. You can also send the same amount of money to a distant relief organization and probably save a child's life there, although you will never know which child benefits. If saving the nearby child is an obvious duty, do you owe the same sacrifice to the distant child?", source(W, "Famine, Affluence, and Morality", "https://en.wikipedia.org/wiki/Famine,_Affluence,_and_Morality")),
    entry("The shared pasture", "A village shares a pasture. Each herder can add one more animal and receive immediate income, but if too many do so, the grass will fail and every herd will suffer. Everyone knows that a single extra animal will not cause the collapse, and no individual herder can enforce restraint. Should you add your animal, ask the others to sacrifice together, or support a rule that limits everyone's private gain to protect the commons?", source(W, "Tragedy of the commons", "https://en.wikipedia.org/wiki/Tragedy_of_the_commons")),
    entry("The ultimatum offer", "A stranger is given $100 and told to offer you any share. If you accept, both of you receive the proposed amounts; if you reject the offer, neither receives anything. The stranger offers you $2 and keeps $98. You could punish the unfairness at a cost to yourself, or accept money that may be useful. Should you accept the offer, reject it, or negotiate even though the rules permit no counteroffer?", source(W, "Ultimatum game", "https://en.wikipedia.org/wiki/Ultimatum_game")),
    entry("The veil of ignorance", "You must choose the basic rules of a new society before learning whether you will be rich or poor, healthy or disabled, powerful or marginalized, talented or dependent on others. You may choose equal outcomes, unequal rewards for effort, a strong safety net, or a system that maximizes total prosperity. Once the veil lifts, you must live under the rules you selected. Which inequalities, if any, would you permit without knowing where you will land?", source(W, "Original position", "https://en.wikipedia.org/wiki/Original_position")),
    entry("The crowded lifeboat", "Your lifeboat has fifty people aboard and enough supplies for ten more. One hundred exhausted swimmers are approaching after a shipwreck. If everyone climbs aboard, the boat will likely capsize; if you keep the boat stable, many swimmers will die. Some are children, some are injured, and some ignored earlier evacuation instructions. Who should be admitted, and should need, age, responsibility, a lottery, or the chance to help the boat determine the places?", source(W, "Lifeboat ethics", "https://en.wikipedia.org/wiki/Lifeboat_ethics")),
    entry("Obedience in the laboratory", "A researcher in a white coat instructs you to continue pressing switches that appear to deliver increasingly painful shocks to a stranger who answers questions incorrectly. The stranger pleads for the experiment to stop, but the researcher says the study requires you to continue and assures you that no permanent injury is occurring. Should you obey the authority, refuse, or continue only until you have independent proof that the shocks are real?", source(W, "Milgram experiment", "https://en.wikipedia.org/wiki/Milgram_experiment")),
    entry("The invisible ring", "You find a ring that makes you invisible whenever you turn its stone. No camera, witness, or magical test can reveal what you do while wearing it, and there is no chance of punishment. You could take money from a wealthy stranger, expose a corrupt official, rescue someone from danger, or satisfy a private desire. Does justice require you to act fairly even when reputation and consequences disappear, or does perfect secrecy change what you owe other people?", source(W, "Ring of Gyges", "https://en.wikipedia.org/wiki/Ring_of_Gyges")),
    entry("The bomber and the civilians", "A bomber pilot can destroy a weapons factory that is supplying an invading army, but the attack will almost certainly kill civilians living in nearby homes. The pilot's aim is the factory, not the civilians, and waiting for a more precise weapon will allow more soldiers to die. Is the raid permissible because the civilian deaths are foreseen but not intended, or is knowingly causing those deaths still wrong?", source(W, "Principle of double effect", "https://en.wikipedia.org/wiki/Principle_of_double_effect")),
    entry("The child who would otherwise not exist", "A parent can have a child now, knowing that the child will face a difficult but worthwhile life, or wait two years for treatment that would likely allow a healthier child to be born. Waiting would not improve the first child's life; it would mean a different child exists instead. Is it morally permissible to choose which possible person comes into existence based on expected wellbeing?", source(W, "Non-identity problem", "https://en.wikipedia.org/wiki/Non-identity_problem")),
    entry("The impossible choice", "An armed authority tells a parent that one of two children will be killed, but both will die if the parent refuses to choose. The parent cannot fight, bargain, or save both. Is choosing one child a moral act, an act under coercion for which the authority bears all blame, or a wrong that remains wrong even when refusal guarantees a worse outcome?", source(W, "Sophie's Choice", "https://en.wikipedia.org/wiki/Sophie%27s_Choice")),
    entry("The good place and the suffering child", "A prosperous city is peaceful and joyful because its citizens' comfort depends on one neglected child being kept alone in misery. Every adult is told the truth when they come of age. If the child is released, the city's prosperity will end; if someone walks away, they reject the bargain without rescuing the child. Should the citizens accept the bargain, leave, or try to dismantle it even if everyone suffers?", source(W, "The Ones Who Walk Away from Omelas", "https://en.wikipedia.org/wiki/The_Ones_Who_Walk_Away_from_Omelas")),
    entry("Political dirty hands", "A leader can prevent a violent coup only by authorizing a secret operation that violates a moral rule the leader publicly promised to respect. If the operation succeeds, thousands may be spared and the violation may never become known; if the leader refuses, the coup may succeed. Can a leader be morally required to do something they must later admit was wrong, or does a good outcome fail to cleanse the act?", source(W, "Dirty hands", "https://en.wikipedia.org/wiki/Dirty_hands")),
    entry("The repugnant population", "A policy could produce a small population whose lives are extraordinarily good, or a much larger population whose lives are barely worth living but still positive. A further increase would eventually produce a population whose total welfare is greater only because there are more people. Should a policy choose the larger population, the better lives, or reject comparisons that treat the existence of additional people as a reason to accept worse lives?", source(W, "Repugnant conclusion", "https://en.wikipedia.org/wiki/Repugnant_conclusion")),

    entry("Who is accountable for the autonomous car?", "A self-driving test vehicle strikes and kills a pedestrian. The safety driver was watching the road but did not take control, the software team knew the system had edge-case failures, the company had a testing schedule, and regulators allowed the trial. The pedestrian's family wants one person held responsible, but the failure came from a chain of decisions. Who should answer for the death, and what kind of accountability would prevent the next one?", source(E, "AI & Accountability: Who’s at the Wheel?", "https://ethicsunwrapped.utexas.edu/case-study/a-i-accountability-whos-at-the-wheel")),
    entry("The family DNA database", "A consumer buys a home DNA test for ancestry and agrees to broad terms about research and data sharing. Years later, investigators use a public genealogy match from a relative to identify a suspect in a violent crime. The match may help convict the guilty and exonerate the innocent, but the customer did not expect their genetic information to become a law-enforcement tool, and relatives never consented. Should the database be available for such searches, and who gets to decide?", source(E, "Ethical Use of Home DNA Testing", "https://ethicsunwrapped.utexas.edu/case-study/ethical-use-of-home-dna-testing")),
    entry("The file-sharing shortcut", "A file-sharing service lets millions of people obtain music without paying the artists or producers. It gives listeners access, challenges an expensive distribution system, and helps inspire later subscription services, but it also makes unauthorized copying easy and shifts costs onto people who created the work. Should a user download the music, should the service continue operating, or does a beneficial innovation remain wrong when it violates creators' rights?", source(E, "Digital Downloads", "https://ethicsunwrapped.utexas.edu/case-study/digital-downloads")),
    entry("The Daraprim price decision", "A company buys the rights to Daraprim, an old medicine used for toxoplasmosis and other serious infections, and raises the price from $13.50 to $750 per tablet. The CEO says profits could fund research and that the medicine is a small part of national health spending; doctors warn that some vulnerable patients need it for life and hospitals may be unable to stock it. Is the price defensible as a business decision, or does access to an essential medicine create a duty to keep it affordable?", source(E, "Daraprim Price Hike", "https://ethicsunwrapped.utexas.edu/video/daraprim-price-hike")),
    entry("The EpiPen price", "A company raises the price of a two-pack of EpiPens, a life-saving emergency treatment for severe allergic reactions. Executives point to business costs and the need to sustain a profitable company, while families and schools say the price makes it harder to keep the medicine available when a reaction can become fatal in minutes. How should a company balance profit, executive compensation, innovation, and the obligation to keep an emergency medicine within reach?", source(E, "EpiPen: Out of Reach", "https://ethicsunwrapped.utexas.edu/video/epipen-out-of-reach")),
    entry("The Theranos promise", "A health company tells investors and patients that its technology can run many blood tests from a finger prick, while internal doubts remain about whether the system works as advertised. Revealing the doubts could end the company and its promised medical access; hiding them could expose patients to incorrect results and investors to fraud. When does confidence in an unfinished innovation become a duty to disclose uncertainty?", source(E, "Theranos’ Bad Blood", "https://ethicsunwrapped.utexas.edu/video/theranos-bad-blood")),
    entry("The breach of credit data", "A company that holds sensitive credit information suffers a major breach after security weaknesses were left unaddressed. The company can disclose the breach quickly, accepting panic and financial damage, or delay until it understands the scope and has a fix. What does the company owe people whose data it collected, and is protecting its reputation ever a legitimate reason to delay warning them?", source(E, "Equifax’s Breach of Trust", "https://ethicsunwrapped.utexas.edu/video/equifaxs-breach-of-trust")),
    entry("The emissions defeat device", "An automaker sells diesel vehicles advertised as clean, while software detects laboratory tests and changes the vehicles' behavior only during testing. The company can disclose the deception and face recalls, costs, and lost trust, or argue that the vehicles meet customer expectations in ordinary driving. Is a product acceptable when it passes a formal test by manipulating the test rather than meeting its purpose?", source(E, "Volkswagen’s Emissions Evasion", "https://ethicsunwrapped.utexas.edu/video/volkswagens-emissions-evasion")),
    entry("The champion who doped", "A cyclist competes in a sport where performance-enhancing drugs are widespread. He can dope to keep pace with rivals and preserve a team, sponsors, and career, or refuse and compete at a disadvantage while others may gain the rewards. If the sport's culture has made clean competition unrealistic, does using the same methods level the field or betray the meaning of fair competition?", source(E, "Armstrong’s Doping Downfall", "https://ethicsunwrapped.utexas.edu/video/armstrongs-doping-downfall")),
    entry("The donor's mistaken gift", "An intern learns that a donor made a large gift to a nonprofit while misunderstanding what the organization would do with it. Correcting the misunderstanding may cost the nonprofit essential funding; staying quiet lets the organization keep money given under misleading assumptions. Should the intern speak up, and should the organization return a gift that was legally completed but ethically misinformed?", source(E, "Full Disclosure: Manipulating Donors", "https://ethicsunwrapped.utexas.edu/case-study/full-disclosure-manipulating-donors")),
    entry("Snowden's disclosure", "A government contractor releases classified documents showing the existence and scale of government surveillance programs. He breaks secrecy agreements and may harm intelligence operations, but argues that citizens have a right to know what is being done in their name and that legal channels were inadequate. Is the disclosure an ethical act of whistleblowing, an unacceptable breach of trust, or both?", source(E, "Edward Snowden: Traitor or Hero?", "https://ethicsunwrapped.utexas.edu/case-study/edward-snowden-traitor-hero")),
    entry("The Ebola intervention", "During an Ebola outbreak, a government considers sending military personnel to help deliver supplies, enforce quarantines, and build treatment capacity. Military logistics could save lives, but the presence of soldiers may frighten residents, undermine trust, and make communities less willing to seek care. Should outside power intervene, and how should it weigh speed against local autonomy and trust?", source(E, "Ebola & American Intervention", "https://ethicsunwrapped.utexas.edu/case-study/ebola-american-intervention")),
    entry("Prenatal diagnosis and choice", "A prenatal test reveals a serious genetic condition. The parents must decide whether to continue the pregnancy, while also confronting what the decision communicates about people already living with the condition, what burdens the family can bear, and how much authority parents should have over reproductive choices. Should the decision focus on expected suffering, parental freedom, disability justice, or some combination?", source(E, "Prenatal Diagnosis & Parental Choice", "https://ethicsunwrapped.utexas.edu/case-study/prenatal-diagnosis-parental-choice")),
    entry("A clinician's personal objection", "A clinical social worker's religious or moral beliefs conflict with a client's identity or requested service. The worker wants to avoid participating in something they believe is wrong, while professional duties require nondiscrimination, cultural competence, and service to the client. Should the worker provide the service, arrange a prompt transfer, or refuse even if refusal limits the client's access to care?", source(E, "Freedom vs. Duty in Clinical Social Work", "https://ethicsunwrapped.utexas.edu/case-study/freedom-vs-duty-in-clinical-social-work")),
    entry("The DNA research conflict", "A university professor leads a study on hydraulic-fracturing risks while receiving substantial payments and stock from a drilling company affected by the result. The professor says the financial relationship did not determine the findings and disclosure would not change the science. Should the study be trusted, withdrawn, independently reviewed, or published with the conflict prominently disclosed?", source(E, "Research Conflicts at UT Austin", "https://ethicsunwrapped.utexas.edu/video/research-conflicts-at-ut-austin")),
    entry("The reporter's poll", "A news organization covers a sports championship while also conducting polls that influence the public conversation about which teams deserve recognition. The organization can publish the poll as news, disclose its role and possible conflict, or stop covering the subject. Can journalism fairly report on a story when its own reporting helps create the story?", source(E, "Covering Yourself? Journalists and the Bowl Championship", "https://ethicsunwrapped.utexas.edu/case-study/covering-journalists-bowl-championship-series")),
    entry("The athlete's cover image", "A sports magazine profiles an accomplished woman athlete, but the proposed cover emphasizes her body and attractiveness more than her athletic achievement. The image may sell more magazines and reflect common audience demand, while the athlete argues that it reduces her to appearance. Should the magazine follow market incentives, represent the athlete on her sporting merits, or give her control over the image?", source(E, "Covering Female Athletes", "https://ethicsunwrapped.utexas.edu/case-study/covering-female-athletes")),
    entry("Dr. V's magical putter", "A journalist investigates a golf putter and discovers that its inventor lied about parts of her professional history and wanted her private life left out of the story. The journalist publishes details that include her transgender identity despite an earlier agreement to focus on the science; the article is defended as exposing deception and criticized as an unnecessary invasion that may have contributed to her suicide. Should the journalist publish the personal details, honor the agreement, or stop the story?", source(E, "Dr. V's Magical Putter", "https://ethicsunwrapped.utexas.edu/case-study/dr-vs-magical-putter")),
    entry("The cyber-harassment response", "A student posts defamatory material about a teacher online. The teacher confronts the student in class and posts a video of that confrontation, turning a private disciplinary matter into another public spectacle. Should the teacher respond publicly, use formal channels, or remain silent to avoid amplifying the harm?", source(E, "Cyber Harassment", "https://ethicsunwrapped.utexas.edu/case-study/cyber-harassment")),
    entry("The fracking study disclosure", "A university research study concludes that hydraulic fracturing did not contaminate groundwater, but its lead professor had undisclosed financial ties to a drilling company. The professor says he coordinated rather than altered the research; critics say the conflict undermines trust in the result. Should the university publish the study with a disclosure, commission a new study, or retract it?", source(E, "Research Conflicts at UT Austin", "https://ethicsunwrapped.utexas.edu/video/research-conflicts-at-ut-austin")),
]


# College-focused cases are kept separate so the game can offer a campus pack
# without mixing its source material into the general-purpose catalog.
COLLEGE_ENTRIES = [
    entry("The admissions side door", "A parent is told that a university's normal admissions process can be bypassed through a private consultant who promises to present the applicant as an athlete. The student is qualified enough to attend, but the family would be using money and a false story to obtain a scarce place. Should the parent proceed, refuse, or tell the university what the consultant proposed?", source(E, "The Varsity Blues Scandal", "https://ethicsunwrapped.utexas.edu/case-study/the-varsity-blues-scandal")),
    entry("The coach's false roster", "A university coach is asked to certify a wealthy applicant as a recruited athlete even though the student has never competed in the sport. The coach could protect the program's funding and accept a promised donation, but the certification would displace applicants admitted honestly and make the coach part of a fraud. Should the coach sign, refuse, or report the request?", source(E, "The Varsity Blues Scandal", "https://ethicsunwrapped.utexas.edu/case-study/the-varsity-blues-scandal")),
    entry("The paper class request", "A university adviser is asked to place athletes in a nominal course that requires little or no work so they can remain eligible. The adviser knows the students are under pressure and that refusing may cost them scholarships, but approving the arrangement turns grades into a service rather than an assessment. Should the adviser protect the students' eligibility, insist on real coursework, or report the request?", source(E, "Academic Fraud at UNC", "https://ethicsunwrapped.utexas.edu/video/academic-fraud-at-unc")),
    entry("The department's empty course", "A department has created a course on paper, but attendance and substantive assignments are not being required and athletes receive high grades. Closing it immediately could invalidate transcripts and harm students who relied on those credits; leaving it open continues a system that privileges athletic eligibility. Should the chair close the course, review every grade, or protect the students from the institution's own failure?", source(E, "Academic Fraud at UNC", "https://ethicsunwrapped.utexas.edu/video/academic-fraud-at-unc")),
    entry("The report to campus police", "A campus police officer receives an allegation of sexual assault involving a prominent athlete. A public investigation could support the survivor and protect future students, but mishandling the case could expose private details, damage due process, and intensify public pressure before facts are established. Should the officer report immediately, conduct a confidential inquiry first, or defer to university administrators?", source(E, "Baylor's Silence on Sexual Assault", "https://ethicsunwrapped.utexas.edu/video/baylors-silence-on-sexual-assault")),
    entry("The coach's warning", "A coach hears a credible warning that a player may have assaulted another student. Reporting it may cost the team its star player and bring scrutiny to the program; keeping the matter inside the athletic department may preserve a season but leave a possible victim without protection. Is the coach's first duty to the team, the accused student, the person reporting, or the wider campus?", source(E, "Baylor's Silence on Sexual Assault", "https://ethicsunwrapped.utexas.edu/video/baylors-silence-on-sexual-assault")),
    entry("The second warning", "A university administrator receives a second report that an adult connected to a powerful sports program may have abused a young person. The first report was never fully acted on, and reopening it will expose the university to legal and reputational harm. Should the administrator protect the institution from a scandal, or report the information even without certainty that a crime occurred?", source(E, "The Sandusky Scandal", "https://ethicsunwrapped.utexas.edu/case-study/the-sandusky-scandal")),
    entry("The protest email", "After racially charged incidents, students protest and a faculty member sends an email asking colleagues to consider whether campus traditions and costumes can cause harm. Some students see the message as necessary criticism; others see it as an attack on free expression and academic independence. Should the university defend the speaker, condemn the message, or leave the dispute to students and faculty?", source(E, "Freedom of Speech on Campus", "https://ethicsunwrapped.utexas.edu/case-study/freedom-speech-campus")),
    entry("The speaker and the threatened event", "A university has invited a controversial speaker. Protesters say the invitation legitimizes hateful ideas, while administrators say cancelling it would let threats determine who may speak. Keeping the event could create a safety risk and burden students; cancelling it could establish a precedent against unpopular views. Should the university host it, move it, or withdraw the invitation?", source(E, "Freedom of Speech on Campus", "https://ethicsunwrapped.utexas.edu/case-study/freedom-speech-campus")),
    entry("The team social-media ban", "A college coach bans players from using Twitter during the season because posts can embarrass the team and sponsors. The rule may reduce harassment and protect a shared public image, but it also controls students' speech outside practice and may silence criticism. Should the players accept the ban, challenge it, or agree only to rules against threats and private-information leaks?", source(E, "Sacking Social Media in College Sports", "https://ethicsunwrapped.utexas.edu/case-study/sacking-social-media-college-sports")),
    entry("The stolen final", "A student crawls through a university building to steal a final exam before the test. The student can return it anonymously and claim no one was harmed, or confess and risk suspension, a criminal investigation, and loss of the course. Should the professor focus on punishment, repair the assessment and show mercy, or treat the theft as a serious breach even if the student never used the questions?", source(E, "Final Exam Heist", "https://ethicsunwrapped.utexas.edu/video/final-exam-heist")),
    entry("The friend at the door", "A student realizes that a friend plans to enter a professor's office and take an exam. Stopping the friend may preserve academic fairness but could end the friendship and trigger severe discipline; staying silent makes the student part of a planned theft. Should the student intervene, report the plan, or wait to see whether the friend changes their mind?", source(E, "Final Exam Heist", "https://ethicsunwrapped.utexas.edu/video/final-exam-heist")),
    entry("The compromised exam", "A professor learns that a final exam may have been stolen shortly before students are scheduled to take it. Replacing the exam inconveniences everyone and may reveal a security failure; using it risks rewarding students who saw it and unfairly accusing those who did not. Should the professor cancel, replace, delay, or administer the compromised exam while investigating?", source(E, "Final Exam Heist", "https://ethicsunwrapped.utexas.edu/video/final-exam-heist")),
    entry("The silent witness to cheating", "A student is offered a copy of a stolen exam but refuses to use it. Reporting the source could protect classmates who prepared honestly, yet it could also expose a friend and cause the entire class to retake the exam. Should the student report what happened, return the copy without explanation, or keep silent because they did not cheat?", source(E, "Final Exam Heist", "https://ethicsunwrapped.utexas.edu/video/final-exam-heist")),
    entry("The recruiting payment", "A sports executive offers money to a college athlete's family and asks a coach to steer the athlete toward a sponsored university. The payment could cover tuition and support the family, but it turns an educational choice into a transaction and gives the athlete an advantage unavailable to others. Should the family accept, disclose the offer, or refuse even if the money would change their future?", source(E, "Steering Student Athletes", "https://ethicsunwrapped.utexas.edu/video/steering-student-athletes")),
    entry("The athlete's adviser", "An athlete's adviser learns that a shoe company is secretly paying coaches to influence recruiting. Exposing the arrangement may protect fair competition but could cost the athlete a scholarship, sponsorship, or place on the team. Should the adviser protect the athlete's immediate opportunity, report the scheme, or let the athlete decide after hearing the risks?", source(E, "Steering Student Athletes", "https://ethicsunwrapped.utexas.edu/video/steering-student-athletes")),
    entry("The prison simulation", "A university researcher assigns student volunteers to act as prisoners or guards in a simulated prison. The study's value depends on the roles feeling real, but participants begin showing distress and some guards behave abusively. Should the researcher stop the study, continue because the findings may matter, or rely on the consent form and scheduled end date?", source(W, "Stanford prison experiment", "https://en.wikipedia.org/wiki/Stanford_prison_experiment")),
    entry("The tribe's blood samples", "A university obtains blood samples from members of an Indigenous community for diabetes research. Years later, researchers use the samples for unrelated studies the community did not expect, including ancestry and migration research. Should the university return or destroy the samples, seek new consent, or treat the original broad consent as sufficient?", source(W, "Havasupai Indian Tribe v. Arizona Board of Regents", "https://en.wikipedia.org/wiki/Havasupai_Indian_Tribe_v._Arizona_Board_of_Regents")),
    entry("The hidden news feed", "A university-affiliated research team helps a social-media company test whether quietly changing users' news feeds changes their emotions. The study could reveal how online systems affect wellbeing, but users were not told they were research participants and cannot easily understand what was altered. Is the social value enough to justify the lack of specific consent?", source(W, "Facebook emotional contagion experiment", "https://en.wikipedia.org/wiki/Facebook_emotional_contagion_experiment")),
    entry("The infant conditioning study", "A researcher proposes to condition fear in an infant by repeatedly pairing a harmless object with a frightening noise. The work might illuminate how phobias develop, but the infant cannot consent and the fear may persist after the study. Should the research proceed if it could produce useful knowledge, or is deliberately creating distress in a child unacceptable?", source(W, "Little Albert experiment", "https://en.wikipedia.org/wiki/Little_Albert_experiment")),
    entry("The admissions rule after the court decision", "A university wants a diverse class after a court decision limits the use of race in admissions. It can consider essays about lived experience, give more weight to socioeconomic disadvantage, or use race-neutral preferences that may produce less diversity. Which approach best balances equal treatment, remedying exclusion, and selecting students as individuals?", source(O, "Students for Fair Admissions v. Harvard", "https://www.supremecourt.gov/opinions/22pdf/20-1199_hgdj.pdf")),
    entry("The parents asking for grades", "A college parent demands access to an adult student's grades after learning that the student is struggling. The parent pays tuition and threatens to withdraw support, but the student expects education records to remain private. Should the university disclose the grades, refuse absent the student's consent, or treat financial dependence as a reason for an exception?", source(O, "Family Educational Rights and Privacy Act (FERPA)", "https://studentprivacy.ed.gov/faq/can-parents-view-childs-post-secondary-education-record")),
    entry("The incomplete consent form", "A university study needs student volunteers, but explaining every hypothesis could change how participants behave and weaken the results. The research team can use limited disclosure with a prompt debriefing, or explain everything and accept less reliable data. When is incomplete information compatible with informed consent, and what risks can never be withheld?", source(O, "The Belmont Report", "https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/read-the-belmont-report/index.html")),
    entry("The scholarship athlete's union", "College football players organize to bargain collectively over scholarships, medical care, and the demands of their sport. A union could give athletes a voice and address unequal power, but the university argues that students are not employees and that bargaining could disrupt scholarships and competition. Should the players unionize, and what obligations does the university owe them?", source(W, "Amateurism in the NCAA", "https://en.wikipedia.org/wiki/Amateurism_in_the_NCAA")),
]


def main() -> None:
    all_entries = CATALOG + COLLEGE_ENTRIES
    seen_themes: set[str] = set()
    seen_texts: set[str] = set()
    for number, item in enumerate(all_entries, start=1):
        item["id"] = f"sourced-{number:04d}"
        if item["theme"] in seen_themes or item["text"] in seen_texts:
            raise ValueError(f"duplicate dilemma at {number}")
        seen_themes.add(item["theme"])
        seen_texts.add(item["text"])
        if not item["source"].get("url"):
            raise ValueError(f"missing source URL at {number}")
    OUTPUT.write_text(json.dumps(all_entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(all_entries)} sourced dilemmas to {OUTPUT}")


if __name__ == "__main__":
    main()
